const OutletProduct = [
  {
    id: "1",
    name: "Ryzen 3 3200G 4.6GHz Turbo + Radeon Vega 8 AM4 Wraith Stealth Cooler",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "2",
    name: "Ryzen 3 4100 - No Cooler OEM",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "3",
    name: "Ryzen 5 3600 4.2GHz Turbo AM4 Wraith Stealth Cooler",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "4",
    name: "Ryzen 5 5600x 4.6GHZ Turbo + Wraith Stealth Cooler",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "5",
    name: "Ryzen 7 5700G 4.6GHz Turbo + Wraith Stealth Cooler",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "6",
    name: "Ryzen 7 5700X 4.6GHz Turbo AM4 - No Cooler",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "7",
    name: "Ryzen 7 7700 5.3GHz Turbo AM5",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "8",
    name: "Ryzen 7 5700G",
    price: "1400",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "2",
    name: "I7 10700",
    price: "1500",
    category: "Cpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "3",
    name: "RTX 3080",
    price: "2000",
    category: "Gpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "4",
    name: "RX 6700 XT",
    price: "1800",
    category: "Gpu",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "5",
    name: "X570 ASUS STRIX",
    price: "1000",
    category: "Motherboard",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "6",
    name: "A520 ASUS STRIX",
    price: "900",
    category: "Motherboard",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "7",
    name: "16GB DDR4 HYPERX",
    price: "500",
    category: "Memory-ram",
    img: "../src/assets/img/ryzen7.png",
  },
  {
    id: "8",
    name: "Nvme2g 480GB",
    price: "300",
    category: "Disk",
    img: "../src/assets/img/ryzen7.png",
  },
];
export default OutletProduct;
